name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - dev

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Check
        run: ./gradlew check

      - name: Build Minecraft mods
        run: ./gradlew buildMinecraftMods

      - name: Capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ebsl-fabric-artifacts
          path: build/mc/**/fabric/libs/*.jar
          if-no-files-found: error
